# frozen_string_literal: true

require_relative "psn_client/version"
require_relative "psn_client/errors"
require_relative "psn_client/auth"
require_relative "psn_client/connection"
require_relative "psn_client/paginator"
require_relative "psn_client/models/mapping"
require_relative "psn_client/models/price"
require_relative "psn_client/models/catalog_item"
require_relative "psn_client/models/user_search_result"
require_relative "psn_client/models/star_rating"
require_relative "psn_client/models/store_product"
require_relative "psn_client/models/store_concept"
require_relative "psn_client/models/game_help"
require_relative "psn_client/models/game_title"
require_relative "psn_client/models/library_title"
require_relative "psn_client/models/purchased_game"
require_relative "psn_client/models/profile"
require_relative "psn_client/models/presence"
require_relative "psn_client/models/device"
require_relative "psn_client/models/shareable_link"
require_relative "psn_client/models/trophy_title"
require_relative "psn_client/models/trophy"
require_relative "psn_client/models/trophy_summary"
require_relative "psn_client/models/title_trophy_summary"
require_relative "psn_client/models/trophy_group"
require_relative "psn_client/models/transaction"
require_relative "psn_client/models/entitlement"
require_relative "psn_client/models/wishlist_item"
require_relative "psn_client/models/content_rating"
require_relative "psn_client/models/media_item"
require_relative "psn_client/models/compatibility_notices"
require_relative "psn_client/models/legal_text"
require_relative "psn_client/models/edition"
require_relative "psn_client/models/plus_offer"
require_relative "psn_client/models/user"
require_relative "psn_client/models/friendship_summary"
require_relative "psn_client/models/installed_title"
require_relative "psn_client/models/console_storage"
require_relative "psn_client/resources/users"
require_relative "psn_client/resources/games"
require_relative "psn_client/resources/trophies"
require_relative "psn_client/resources/store"
require_relative "psn_client/resources/profiles"
require_relative "psn_client/resources/search"
require_relative "psn_client/resources/social"
require_relative "psn_client/resources/devices"
require_relative "psn_client/resources/catalog"
require_relative "psn_client/client"

# Unofficial PlayStation Network API client.
module PSN
end
