module PSN
  class Collection < SimpleDelegator
    class TotalState < ::Struct[untyped]
      attr_accessor known: bool
      attr_accessor value: Integer?
    end

    def initialize: (Enumerator::Lazy[untyped, untyped] enum,
                     ?total_state: TotalState, ?total_fetcher: (^() -> Integer?)?) -> void
    def total: () -> Integer?
    def map: () { (untyped) -> untyped } -> Collection
  end
end
