module PSN
  class GameTitle < ::Data
    def self.from_api: (::Hash[String, untyped] hash) -> GameTitle
    def self.new: (**untyped) -> instance

    attr_reader name: String?
    attr_reader title_id: String?
    attr_reader platform: String?
    attr_reader play_count: Integer?
    attr_reader first_played_at: Time?
    attr_reader last_played_at: Time?
    attr_reader play_duration: Integer?
    attr_reader raw: ::Hash[String, untyped]
  end
end
